receivers:
  filelog:
    start_at: end
    include:
      - /usr/logs/data-transfer*.json*

exporters:
  otlphttp:
    endpoint: http://loki:3100/otlp
    sending_queue:
      enabled: true
      num_consumers: 4
      queue_size: 1000

processors:
  batch:
    send_batch_size: 1000
    send_batch_max_size: 2000
    timeout: 5s
  attributes:
    # Adding a Loki label based on OTLP attribute "log.file.name" happens in two steps:
    actions:
      # Insert a new attribute "file_name" from the OTLP attribute "log.file.name"
      - action: insert
        key: filename
        from_attribute: log.file.name
      # Add hint for Loki that the attribute "filename" should be placed as a Loki label
      - action: insert
        key: loki.attribute.labels
        value: filename

extensions:
  health_check:

service:
  extensions: [ health_check ]
  pipelines:
    logs:
      receivers: [ filelog ]
      processors: [ attributes, batch ]
      exporters: [ otlphttp ]
